/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoadTestRouteImport } from './routes/load-test'
import { Route as InterceptRouteImport } from './routes/intercept'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadTestRoute = LoadTestRouteImport.update({
  id: '/load-test',
  path: '/load-test',
  getParentRoute: () => rootRouteImport,
} as any)
const InterceptRoute = InterceptRouteImport.update({
  id: '/intercept',
  path: '/intercept',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/docs': typeof DocsRoute
  '/environments': typeof EnvironmentsRoute
  '/explorer': typeof ExplorerRoute
  '/intercept': typeof InterceptRoute
  '/load-test': typeof LoadTestRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/docs': typeof DocsRoute
  '/environments': typeof EnvironmentsRoute
  '/explorer': typeof ExplorerRoute
  '/intercept': typeof InterceptRoute
  '/load-test': typeof LoadTestRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/docs': typeof DocsRoute
  '/environments': typeof EnvironmentsRoute
  '/explorer': typeof ExplorerRoute
  '/intercept': typeof InterceptRoute
  '/load-test': typeof LoadTestRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/auth'
    | '/console'
    | '/docs'
    | '/environments'
    | '/explorer'
    | '/intercept'
    | '/load-test'
    | '/logs'
    | '/settings'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/auth'
    | '/console'
    | '/docs'
    | '/environments'
    | '/explorer'
    | '/intercept'
    | '/load-test'
    | '/logs'
    | '/settings'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/auth'
    | '/console'
    | '/docs'
    | '/environments'
    | '/explorer'
    | '/intercept'
    | '/load-test'
    | '/logs'
    | '/settings'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  ConsoleRoute: typeof ConsoleRoute
  DocsRoute: typeof DocsRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  ExplorerRoute: typeof ExplorerRoute
  InterceptRoute: typeof InterceptRoute
  LoadTestRoute: typeof LoadTestRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/load-test': {
      id: '/load-test'
      path: '/load-test'
      fullPath: '/load-test'
      preLoaderRoute: typeof LoadTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intercept': {
      id: '/intercept'
      path: '/intercept'
      fullPath: '/intercept'
      preLoaderRoute: typeof InterceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  ConsoleRoute: ConsoleRoute,
  DocsRoute: DocsRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  ExplorerRoute: ExplorerRoute,
  InterceptRoute: InterceptRoute,
  LoadTestRoute: LoadTestRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
